const connectableChains = {
  desmos: {
    name: 'Desmos',
    ledgerAppDisplayName: 'Desmos (DSM)',
    image: '/static/images/cryptocurrencies/dsm.svg',
    prefix: 'desmos',
    coinType: 852,
    ledgerAppNames: ['desmos', 'cosmos'],
    chainId: 'desmos-mainnet',
    feeDenom: 'udsm',
  },
  cosmos: {
    name: 'Cosmos Hub',
    ledgerAppDisplayName: 'Cosmos (ATOM)',
    image: '/static/images/cryptocurrencies/atom.png',
    prefix: 'cosmos',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'cosmoshub-4',
    feeDenom: 'uatom',
  },
  akash: {
    name: 'Akash',
    ledgerAppDisplayName: 'Akash (AKT)',
    image: '/static/images/cryptocurrencies/akt.png',
    prefix: 'akash',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'akashnet-2',
    feeDenom: 'uakt',
  },
  osmosis: {
    name: 'Osmosis',
    ledgerAppDisplayName: 'Osmosis (OSMO)',
    image: '/static/images/cryptocurrencies/osmo.svg',
    prefix: 'osmo',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'osmosis-1',
    feeDenom: 'uosmo',
  },
  sentinel: {
    name: 'Sentinel',
    ledgerAppDisplayName: 'Sentinel (DVPN)',
    image: '/static/images/cryptocurrencies/dvpn.png',
    prefix: 'sent',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'sentinelhub-2',
    feeDenom: 'udvpn',
  },
  'crypto.org chain': {
    name: 'Crypto.org',
    ledgerAppDisplayName: 'Crypto.org (CRO)',
    image: '/static/images/cryptocurrencies/cro.png',
    prefix: 'cro',
    coinType: 394,
    ledgerAppNames: ['crypto.org chain', 'cosmos'],
    chainId: 'crypto-org-chain-mainnet-1',
    feeDenom: 'ucro',
  },
  terra: {
    name: 'Terra',
    ledgerAppDisplayName: 'Terra (LUNA)',
    image: '/static/images/cryptocurrencies/terra.png',
    prefix: 'terra',
    coinType: 330,
    ledgerAppNames: ['terra', 'cosmos'],
    chainId: 'columbus-5',
    feeDenom: 'uluna',
  },
  kava: {
    name: 'Kava',
    ledgerAppDisplayName: 'Kava (KAVA)',
    image: '/static/images/cryptocurrencies/kava.png',
    prefix: 'kava',
    coinType: 459,
    ledgerAppNames: ['kava', 'cosmos'],
    chainId: 'kava-7',
    feeDenom: 'ukava',
  },
  regen: {
    name: 'Regen',
    ledgerAppDisplayName: 'Regen (REGEN)',
    image: '/static/images/cryptocurrencies/regen.png',
    prefix: 'regen',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'regen-1',
    feeDenom: 'uregen',
  },
  likecoin: {
    name: 'Likecoin',
    ledgerAppDisplayName: 'Likecoin (LIKE)',
    image: '/static/images/cryptocurrencies/likecoin.png',
    prefix: 'cosmos',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'likecoin-mainnet-2',
    feeDenom: 'nanolike',
  },
  band: {
    name: 'Band Protocol',
    ledgerAppDisplayName: 'Band Protocol (BAND)',
    image: '/static/images/cryptocurrencies/band.png',
    prefix: 'band',
    coinType: 494,
    ledgerAppNames: ['band', 'cosmos'],
    chainId: 'laozi-mainnet',
    feeDenom: 'uband',
  },
  emoney: {
    name: 'e-Money',
    ledgerAppDisplayName: 'E-Money (NGM)',
    image: '/static/images/cryptocurrencies/emoney.png',
    prefix: 'emoney',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'emoney-3',
    feeDenom: 'ungm',
  },
  juno: {
    name: 'Juno',
    ledgerAppDisplayName: 'Juno (JUNO)',
    image: '/static/images/cryptocurrencies/juno.svg',
    prefix: 'juno',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'juno-1',
    feeDenom: 'ujuno',
  },
  secretnetwork: {
    name: 'Secret Network',
    ledgerAppDisplayName: 'Secret Network (SCRT)',
    image: '/static/images/cryptocurrencies/scrt.webp',
    prefix: 'scrt',
    coinType: 529,
    ledgerAppNames: ['cosmos'],
    chainId: 'secret-4',
    feeDenom: 'uscrt',
  },
  sifchain: {
    name: 'Sifchain',
    ledgerAppDisplayName: 'Sifchain (ROWAN)',
    image: '/static/images/cryptocurrencies/rowan.webp',
    prefix: 'sif',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'sifchain-1',
    feeDenom: 'urowan',
  },
  irisnet: {
    name: 'IRISnet',
    ledgerAppDisplayName: 'IRISnet (IRIS)',
    image: '/static/images/cryptocurrencies/iris.svg',
    prefix: 'iaa',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'irishub-1',
    feeDenom: 'uiris',
  },
  persistence: {
    name: 'Persistence',
    ledgerAppDisplayName: 'Persistence (XPRT)',
    image: '/static/images/cryptocurrencies/xprt.png',
    prefix: 'persistence',
    coinType: 750,
    ledgerAppNames: ['persistence', 'cosmos'],
    chainId: 'core-1',
    feeDenom: 'uxprt',
  },
  ixo: {
    name: 'IXO',
    ledgerAppDisplayName: 'IXO',
    image: '/static/images/cryptocurrencies/ixo.png',
    prefix: 'ixo',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'impacthub-3',
    feeDenom: 'uixo',
  },
  bitcanna: {
    name: 'Bitcanna',
    ledgerAppDisplayName: 'Bitcanna',
    image: '/static/images/cryptocurrencies/bcna.svg',
    prefix: 'bcna',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
    chainId: 'bitcanna-1',
    feeDenom: 'ubcna',
  },
  bitsong: {
    name: 'Bitsong',
    ledgerAppDisplayName: 'Bitsong',
    image: '/static/images/cryptocurrencies/btsg.svg',
    prefix: 'btsg',
    coinType: 639,
    ledgerAppNames: ['cosmos'],
    chainId: 'bitsong-2b',
    feeDenom: 'ubtsg',
  },
}

export default connectableChains
