const connectableChains = {
  desmos: {
    name: 'Desmos',
    image: '/static/images/cryptocurrencies/dsm.svg',
    prefix: 'desmos',
    coinType: 852,
    ledgerAppNames: ['desmos', 'cosmos'],
  },
  cosmos: {
    name: 'Cosmos',
    image: '/static/images/cryptocurrencies/atom.png',
    prefix: 'cosmos',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  akash: {
    name: 'Akash',
    image: '/static/images/cryptocurrencies/akt.png',
    prefix: 'akash',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  osmosis: {
    name: 'Osmosis',
    image: '/static/images/cryptocurrencies/osmo.svg',
    prefix: 'osmo',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  sentinel: {
    name: 'Sentinel',
    image: '/static/images/cryptocurrencies/dvpn.png',
    prefix: 'sent',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  cro: {
    name: 'Crypto.org',
    image: '/static/images/cryptocurrencies/cro.png',
    prefix: 'cro',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  terra: {
    name: 'Terra',
    image: '/static/images/cryptocurrencies/terra.png',
    prefix: 'terra',
    coinType: 330,
    ledgerAppNames: ['terra', 'cosmos'],
  },
  regen: {
    name: 'Regen',
    image: '/static/images/cryptocurrencies/regen.png',
    prefix: 'regen',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  likecoin: {
    name: 'Likecoin',
    image: '/static/images/cryptocurrencies/likecoin.png',
    prefix: 'cosmos',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  band: {
    name: 'Band Protocol',
    image: '/static/images/cryptocurrencies/band.png',
    prefix: 'band',
    coinType: 494,
    ledgerAppNames: ['band', 'cosmos'],
  },
  emoney: {
    name: 'e-Money',
    image: '/static/images/cryptocurrencies/emoney.png',
    prefix: 'emoney',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  juno: {
    name: 'Juno',
    image: '/static/images/cryptocurrencies/juno.svg',
    prefix: 'juno',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  secretnetwork: {
    name: 'Secret Network',
    image: '/static/images/cryptocurrencies/scrt.webp',
    prefix: 'scrt',
    coinType: 529,
    ledgerAppNames: ['cosmos'],
  },
  sifchain: {
    name: 'Sifchain',
    image: '/static/images/cryptocurrencies/rowan.webp',
    prefix: 'juno',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  irisnet: {
    name: 'IRISnet',
    image: '/static/images/cryptocurrencies/iris.svg',
    prefix: 'iaa',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  persistence: {
    name: 'Persistence',
    image: '/static/images/cryptocurrencies/xprt.png',
    prefix: 'persistence',
    coinType: 750,
    ledgerAppNames: ['persistence', 'cosmos'],
  },
  ixo: {
    name: 'IXO',
    image: '/static/images/cryptocurrencies/ixo.png',
    prefix: 'ixo',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  bitcanna: {
    name: 'Bitcanna',
    image: '/static/images/cryptocurrencies/bcna.svg',
    prefix: 'bcna',
    coinType: 118,
    ledgerAppNames: ['cosmos'],
  },
  bitsong: {
    name: 'Bitsong',
    image: '/static/images/cryptocurrencies/btsg.svg',
    prefix: 'btsg',
    coinType: 639,
    ledgerAppNames: ['cosmos'],
  },
}

export default connectableChains
